spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/apdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ash@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashwithasujitha@gmail.com
spring.mail.password=etnf lwuo yhnk jbut
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
